### ISSUE TITLE
strage error alreay on including the lib while using mocha

### ISSUE THREAD

**Issue by sebs** [m-radzikowski/aws-sdk-client-mock#109]
**Checklist**

- [x ] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

**Bug description**

When using the lib with mocha, ts-node in latest version I get a error as soon as I import it to my tests

```
Error: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
    at Object.resolveTypeReferenceDirective (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:42537:18)
    at /Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/ts-node/src/resolver-functions.ts:131:51
    at Array.map (<anonymous>)
    at Object.resolveTypeReferenceDirectives (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/ts-node/src/resolver-functions.ts:130:31)
    at actualResolveTypeReferenceDirectiveNamesWorker (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:116674:163)
    at resolveTypeReferenceDirectiveNamesWorker (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:116974:26)
    at processTypeReferenceDirectives (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118456:31)
    at findSourceFileWorker (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118341:21)
    at findSourceFile (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118196:26)
    at processImportedModules (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118602:25)
    at findSourceFileWorker (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118347:17)
    at findSourceFile (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118196:26)
    at processImportedModules (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118602:25)
    at findSourceFileWorker (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118347:17)
    at findSourceFile (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118196:26)
    at /Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118148:85
    at getSourceFileFromReferenceWorker (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118114:34)
    at processSourceFile (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:118148:13)
    at processRootFile (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:117949:13)
    at /Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:116765:67
    at Object.forEach (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:377:30)
    at Object.createProgram (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:116765:16)
    at synchronizeHostData (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:165086:26)
    at Object.getProgram (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/typescript/lib/typescript.js:165218:13)
    at getOutput (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/ts-node/src/index.ts:914:39)
    at Object.compile (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1174:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:998:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1022:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.exports.requireOrImport (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/mocha/lib/nodejs/esm-utils.js:60:20)
    at async Object.exports.loadFilesAsync (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/mocha/lib/nodejs/esm-utils.js:103:20)
    at async singleRun (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/sebastianschurmann/projects/jo-jobs-viewer/packages/lambda-toc/node_modules/mocha/lib/cli/run.js:374:5)
```

**Reproduction**

```typescript
import { describe, it } from 'mocha';
import { expect } from 'chai';

import { mockClient } from 'aws-sdk-client-mock';

describe('basic test', ()=>{
    it('true is true', ()=>{
        expect(true).to.be.ok
    });
});

```

**Environment**

- Node version: 17.4, 18.6.0
- Testing lib and version:  mocha
- Typescript version: 4.74
- AWS SDK v3 Client mock version: ^1.0.0
- AWS JS SDK libs and versions:
"@aws-sdk/client-s3": "3.142.0"

**Comment by sebs** [comment]
updated mocha  and others to latest fixed the problem.
