### ISSUE TITLE
toHaveReceivedCommandWith only gets the last SNS Message sent

### ISSUE THREAD

**Issue by davidfisher-vf** [m-radzikowski/aws-sdk-client-mock#161]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Test fails reporting that the same message has been sent twice but walking through the code shows one call to the mock with the first Message of 1979.

    Expected SNSClient to receive "PublishCommand" with {"Message": "1979"}
    SNSClient received matching "PublishCommand" 0 times
    Calls:
      1. PublishCommand: {"Message": "1234", "TopicArn": "arn:test"}
      2. PublishCommand: {"Message": "1234", "TopicArn": "arn:test"}
      
When trying to examine the calls the mock received via snsMocks.calls() I get the following exception:
`errorWithCallStack: Error:
            at Function.invoke (/Users/username/CompanyLambda/src/node_modules/sinon/lib/sinon/proxy-invoke.js:65:15)
            at SNSClient.send (/Users/username/CompanyLambda/src/node_modules/sinon/lib/sinon/proxy.js:280:26)
            at send (/Users/username/CompanyLambda/src/index.test.js:39:35)
            at processTicksAndRejections (node:internal/process/task_queues:95:5)
            at Object.<anonymous> (/Users/username/CompanyLambda/src/index.test.js:66:18)`

### Reproduction

```require("aws-sdk-client-mock-jest");
const { mockClient } = require("aws-sdk-client-mock");
const { SNSClient, PublishCommand } = require("@aws-sdk/client-sns");

const db = {
  Company: {
    findAll: async () => [
      {
        company_id: 1979,
      },
      {
        company_id: 1234,
      },
    ],
  },
};
const region = process.env.REGION || "eu-west-1";
const snsClient = new SNSClient({ region });
const snsMock = mockClient(SNSClient);
const handler = async () => {
  let input = {
    TopicArn: "arn:test",
    Message: "",
  };

  const companies = await db.Company.findAll();
  const snsRes = [];

  for await (const company of companies) {
    input.Message = company.company_id.toString();
    let command = new PublishCommand(input);

    try {
      const res = await snsClient.send(command);
      snsRes.push(res);
    } catch (err) {
      console.log(err);
      return;
    }
  }
  return snsRes;
};

beforeEach(() => {
  snsMock.reset();
});

it("should call SNS with a company id", async () => {
  snsMock
    .on(PublishCommand)
    .resolvesOnce({
      MessageId: "1234567-1234567-1234567-1234567",
    })
    .resolvesOnce({
      MessageId: "1234567-1234567-1234567-9994567",
    }, {
        "Message": "1234", 
        "TopicArn": "arn:test"
    });
  const result = await handler();
  const calls = snsMock.calls();
  expect(snsMock).toHaveReceivedCommand(PublishCommand, 2);
  expect(snsMock).toHaveReceivedCommandWith(PublishCommand, {
    Message: "1979",
  });
  expect(snsMock).toHaveReceivedCommandWith(2, PublishCommand, {
    Message: "1234",
  });
});

### Environment

- Node version: 16.20.0 and 18.16.0
- Testing lib and version: Jest 29.5.0
- Typescript version:
- AWS SDK v3 Client mock version: 2.1.1
- AWS JS SDK libs and versions:
    - client-sns: 3.337.0

**Comment by samchungy** [comment]
That would likely be because you're mutating `input`. I assume the matcher only stores a ref to input

**Comment by davidfisher-vf** [comment]
Changing the handler to use two separate input constants with the input.Message hard coded and using two calls to PublishCommand and SNSClient instead of the `for await` loop produces the same test failure.

**Comment by samchungy** [comment]
Your code when I pulled it down had a number of issues:

This seems fine:

```
import { PublishCommand, SNSClient } from '@aws-sdk/client-sns';
import { mockClient } from 'aws-sdk-client-mock';
import 'aws-sdk-client-mock-jest';

const db = {
  Company: {
    findAll: () => [
      {
        company_id: 1979,
      },
      {
        company_id: 1234,
      },
    ],
  },
};
const region = process.env.REGION || 'eu-west-1';
const snsClient = new SNSClient({ region });
const snsMock = mockClient(SNSClient);
const handler = async () => {
  const companies = db.Company.findAll();
  const snsRes = [];

  for await (const company of companies) {
    const input = {
      TopicArn: 'arn:test',
      Message: company.company_id.toString(),
    };
    const command = new PublishCommand(input);

    try {
      const res = await snsClient.send(command);
      snsRes.push(res);
    } catch (err) {
      console.log(err);
      return;
    }
  }
  return snsRes;
};

beforeEach(() => {
  snsMock.reset();
});

it('should call SNS with a company id', async () => {
  snsMock
    .on(PublishCommand)
    .resolvesOnce({
      MessageId: '1234567-1234567-1234567-1234567',
    })
    .resolvesOnce({
      MessageId: '1234567-1234567-1234567-9994567',
    });
  const result = await handler();
  const calls = snsMock.calls();
  expect(snsMock).toHaveReceivedCommand(PublishCommand, 2);
  expect(snsMock).toHaveReceivedCommandWith(PublishCommand, {
    Message: '1979',
    TopicArn: 'arn:test',
  });
  expect(snsMock).toHaveReceivedNthCommandWith(2, PublishCommand, {
    Message: '1234',
    TopicArn: 'arn:test',
  });
});

```

**Comment by m-radzikowski** [comment]
> I assume the matcher only stores a ref to input

Correct. And thanks for taking the time to help here 🙂

I'm closing this issue, but please re-open it if the problem persists.
