### ISSUE TITLE
NodeJS 20 mocking Upload doesn't work

### ISSUE THREAD

**Issue by Angoulema** [m-radzikowski/aws-sdk-client-mock#211]
### Checklist

- [X] I have read [Caveats](https://github.com/m-radzikowski/aws-sdk-client-mock#caveats) documentation and didn't find a solution for this problem there.

### Bug description

Mock of Upload function from @aws-sdk/lib-storage which worked well on Node 16 doesn't work on Nove 20.
Error is thrown during part:
```
const s3UploadStream = new PassThrough();
    s3UploadStream.on('error', (err) => {
      logger.error(err, 'Error on pass through stream');
      throw err;
    });
```
after file is uploaded (according to logs), and test fails.

Error stack is:
```
      at getDataReadable (node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:113:20)
      at getChunkStream (node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:88:20)
      at _Upload.__doConcurrentUpload (node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:269:22)
          at async Promise.all (index 1)
      at _Upload.__doMultipartUpload (node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:366:5)
      at _Upload.done (node_modules/@aws-sdk/lib-storage/dist-cjs/index.js:190:12)
```

Code wasn't changed, the only thing which changed is NodeJS version.
Code itself is working, files are uploading to S3 okay. Only tests don't work now.

### Reproduction

```
import { Upload } from '@aws-sdk/lib-storage';
import { Archiver } from 'archiver';
import { S3Client } from '@aws-sdk/client-s3';
import { PassThrough } from 'stream';

class S3Service {
  private readonly s3: S3Client;

  constructor() {
    this.s3 = new S3Client({ });
  }

public async upload(archiverStream: Archiver, fileName: string, bucket: string) {
    const s3UploadStream = new PassThrough();
    s3UploadStream.on('error', (err) => {
      logger.error(err, 'Error on pass through stream');
      throw err;
    });
   const bucketKey = `${SOME_CONSTANT}/${Date.now()}`;
   const s3Params = {
      Bucket: bucket,
      Key: bucketKey,
      Body: s3UploadStream,
      ContentType: 'application/zip'
    };
   try {
      const parallelUploads3 = new Upload({
        client: this.s3,
        params: s3Params
      });

      parallelUploads3.on('httpUploadProgress', (progress) => {
        logger.debug(progress, 'Uploading file to S3');
      });

      archiverStream.pipe(s3UploadStream);
    
      await parallelUploads3.done();
    } catch (error) {
      logger.error(`Cannot upload file to s3. Key: ${s3Params.Key}, error: ${error}`);
      throw error;
    }
}
}
```

Mock for this method
```
import { mockClient } from 'aws-sdk-client-mock';
import 'aws-sdk-client-mock-jest';
import {
  CreateMultipartUploadCommand, UploadPartCommand, S3Client, CompleteMultipartUploadCommand
} from '@aws-sdk/client-s3';
import { sdkStreamMixin } from '@smithy/util-stream';

const mockS3Client = mockClient(S3Client);
mockS3Client.on(CreateMultipartUploadCommand).resolves({ UploadId: '1' });
mockS3Client.on(UploadPartCommand).resolves({ ETag: '1' });
mockS3Client.on(CompleteMultipartUploadCommand).resolves({ Bucket: 'test', Key: 'directory/name.ext' });

const readStream = new stream.Readable();
readStream.push('hello world');
readStream.push(null); // end of stream

// wrap the Stream with SDK mixin
const sdkStream = sdkStreamMixin(readStream);

const mockArchiverOn = jest.fn();
const mockArchiverFile = jest.fn();
const mockArchiverAppend = jest.fn((passStreamCsv: stream.PassThrough) => {
  passStreamCsv.emit('end');
});
const mockArchiverPipe = jest.fn((passStreamCsv: stream.PassThrough) => {
  const Body = 'x'.repeat(6 * 1024 * 1024); // 6 MB
  passStreamCsv.push(Body);
  passStreamCsv.push(null);
});
const mockArchiverFinalize = jest.fn(() => Promise.resolve({ stream: sdkStream }));
jest.mock('archiver', () => jest.fn().mockImplementation(() => ({
  on: mockArchiverOn,
  file: mockArchiverFile,
  append: mockArchiverAppend,
  finalize: mockArchiverFinalize,
  pipe: mockArchiverPipe
})));

test('some test', async () => {
await handler(testEvent);

expect(mockArchiverAppend).toHaveBeenCalled();
expect(mockS3Client).toReceiveCommand(CreateMultipartUploadCommand);
expect(mockS3Client).toReceiveCommand(UploadPartCommand);
expect(mockS3Client).toReceiveCommand(CompleteMultipartUploadCommand);
})
```

### Environment

- Node version: v20.11.0
- Testing lib and version: Jest 29.7.0
- Typescript version: 4.9
- AWS SDK v3 Client mock version: 3.0.1
- AWS JS SDK libs and versions:
    - @aws-sdk/client-dynamodb: 3.504.0
    - @aws-sdk/client-s3: 3.504.0
    - @aws-sdk/client-sqs: 3.504.0
    - @aws-sdk/lib-storage: 3.504.0
    - @aws-sdk/util-dynamodb: 3.504.0

**Comment by m-radzikowski** [comment]
Please provide a single, simple test example that I can run, without referencing any unknown methods.

A working example with @aws-sdk/lib-storage v3.504.0 and Node.js v20.11.1:

```ts
import {CreateMultipartUploadCommand, S3Client, UploadPartCommand} from '@aws-sdk/client-s3';
import {Upload} from "@aws-sdk/lib-storage";
import {mockClient} from "aws-sdk-client-mock";

const s3Mock = mockClient(S3Client);
s3Mock.on(CreateMultipartUploadCommand).resolves({UploadId: '1'});
s3Mock.on(UploadPartCommand).resolves({ETag: '1'});

it('works', async () => {
	const s3Upload = new Upload({
		client: new S3Client({}),
		params: {
			Bucket: 'mock',
			Key: 'test',
			Body: 'x'.repeat(6 * 1024 * 1024), // 6 MB
		},
	});

	s3Upload.on('httpUploadProgress', (progress) => {
		console.log(progress);
	});

	await s3Upload.done();
});
```
